### ISSUE TITLE
Support Windows runners

### ISSUE THREAD

**Issue by MaxDesiatov** [swift-actions/setup-swift#132]
**Is your feature request related to a problem? Please describe.**
Swift 5.3 is now available on Windows, so it would be great to use this action to install the Swift toolchain on Windows hosts.

**Describe the solution you'd like**
I would like to be able to use this action with Windows runners.

**Comment by fwal** [comment]
Good suggestion! 👍 This depends on #61

**Comment by fwal** [comment]
Additional help will be required to bring this home, please see the pr 👉 #140

**Comment by fwal** [comment]
Support for windows have landed in [1.16.0](https://github.com/swift-actions/setup-swift/releases/tag/v1.16.0) 🎉
