### ISSUE TITLE
Error: Unable to resolve action `swift-actions/setup-swift@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by wadetregaskis** [swift-actions/setup-swift#471]
**Describe the bug**
[Workflow configuration](https://github.com/wadetregaskis/SwiftWeather/blob/6c91be7bf152c20e809a817771d47194c5e5f3d3/.github/workflows/swift.yml).
[Example Action run log](https://github.com/wadetregaskis/SwiftWeather/actions/runs/3048050100/jobs/4912748401).

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): swift-actions/setup-swift@v1
 - Platform (`runs-on`): macos-latest
 - Swift version (`swift-version`): 5.7

**Comment by gregcotten** [comment]
same

**Comment by gregcotten** [comment]
RIP all swift builds on GitHub Actions

**Comment by dvosscricut** [comment]
same

**Comment by bdrelling** [comment]
Same. Ugh.

**Comment by finestructure** [comment]
FWIW, it started failing with this error this morning - so it must have been a commit yesterday that is causing this.

<img width="806" alt="CleanShot 2022-09-14 at 08 40 17@2x" src="https://user-images.githubusercontent.com/65520/190078886-442c5898-8f1a-4d04-9098-a2252feddeb7.png">

**Comment by fwal** [comment]
Sorry everyone, something went awry with the v1 tag during release yesterday, everything should work now. 
For future reference (and I'll add this to the readme) you can always use specific versions as well like `swift-actions/setup-swift@v1.17.0` (together with dependabot to keep it up-to-date).

I apologise for the outtake.

**Comment by finestructure** [comment]
Thanks a lot for the quick fix, can confirm it's working again :)
