### ISSUE TITLE
Github Actions are deprecating Node 12

### ISSUE THREAD

**Issue by BeyondEvil** [swift-actions/setup-swift#484]
This is the message you get in the build:

>Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: swift-actions/setup-swift

We're using `uses: swift-actions/setup-swift@v1`

**Comment by moyerr** [comment]
I noticed this warning in my build pipeline yesterday. Thanks for raising this issue and opening #485!
