### ISSUE TITLE
`set-output` command is deprecated

### ISSUE THREAD

**Issue by zunda-pixel** [swift-actions/setup-swift#490]
**Describe the bug**

GitHub Actions Deprecate Message

```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Workflow configuration (please complete the following information):**
 - Action version: `swift-actions/setup-swift@v1`
 - Platform: `ubuntu-latest`
 - Swift version: `5.7`

**Comment by zunda-pixel** [comment]
`@actions/core`'s version is required `v1.10.0`, but setup-swift's @action/core is `v1.10.0`.
Maybe GitHub Deprecate Message is incorrect.

**Comment by fwal** [comment]
Hi @zunda-pixel! 👋🏻 

Thanks for reporting, the updated `@actions/core` only existed in master, created a new release now 🎉
