### ISSUE TITLE
Swift 5.7.1 not available

### ISSUE THREAD

**Issue by redsun82** [swift-actions/setup-swift#502]
**Describe the bug**
When running the action with `swift-version` 5.7.1 one gets the error `Error: Version "5.7.1" is not available`.

Is this a question of just adding that released version to [swift-versions.ts](https://github.com/swift-actions/setup-swift/blob/5cdaa9161ad1f55ae39a5ea1784ef96de72f95d9/src/swift-versions.ts) and then it would just work?

**Workflow configuration (please complete the following information):**
 - Action version (`uses`): `swift-actions/setup-swift@v1`
 - Platform (`runs-on`): `ubuntu-latest` and `macos-latest`
 - Swift version (`swift-version`): 5.7.1

**Comment by redsun82** [comment]
Ah, I just saw https://github.com/swift-actions/setup-swift/pull/499

**Comment by redsun82** [comment]
Do I understand that #499 is blocked on windows problems? Is there any chance to get the update out at least for other platform in the meantime?

**Comment by keith** [comment]
I don't think it's blocked on windows support, I just pushed to the PR again to not bump windows for now

**Comment by fwal** [comment]
Fixed in #499 and released as 1.20.0 🎉
