### ISSUE TITLE
Status Of Project, Request To Maintain

### ISSUE THREAD

**Issue by brianmichel** [swift-actions/setup-swift#634]
I wanted to check in and see if this project is still being actively maintained. Looking at the backlog of auto-created PR https://github.com/swift-actions/setup-swift/pulls and the list of automatically merged PRs (all from bots) it appears this project is no longer actively maintained. 

If you're looking for a new maintainer, we (The Browser Company of New York) might be interested in picking up maintenance as we're actively doing work on Swift across multiple platforms and could benefit from an up to date version of a GHA setup script that works across all platforms, includes all new versions of Swift, as well as support for non-release builds of the toolchain.

Please let me know!

**Comment by fwal** [comment]
Hi @brianmichel! 👋

Yeah, unfortunately I haven't had the time over that the project deserves as you noted. There have been some attempts to bring in more maintainers in the past but those efforts ended up fruitless.

I'm always open to anything that will keep the project alive and kicking!

**Comment by bsneed** [comment]
@brianmichel don't know if you saw this, but it seems more maintained.  we're moving over to that one on our end.  https://github.com/sersoft-gmbh/swifty-linux-action

**Comment by fwal** [comment]
Yeah totally understandable 🙂

If you only target Linux I also think you can use the official docker images directly (bit then there's no version resolution 😞)

Either way, thanks for reaching out and best of luck! ✌️

**Comment by dabrahams** [comment]
What's really needed is one unified action implementation that works on all the platforms.  @brianmichel  your colleague @compnerd is already maintaining one for Windows.  Maybe that would make a good foundation?  I just ask that you consider improving the UI; the whole branch/tag business on that one is confounding!

**Comment by dabrahams** [comment]
@compnerd we should probably not do this here… https://github.com/compnerd/gha-setup-swift/issues/19#issuecomment-1981172160

**Comment by fwal** [comment]
Yeah there was an initial attempt by SSWG some years ago unify all this and a couple of maintainers of several options came together and we concluded to keep this action going, but it quickly became so that I was still the only maintainer 🙃

I would love to have all platforms running in once action (which they where, although briefly, back in [1.16.0](https://github.com/swift-actions/setup-swift/releases/tag/v1.16.0)) but sadly rest of life got in the way and I haven't had the time to spare to bring Windows back.
